### PR TITLE
Use same dateFormat in all views [Bounty 889]

### PR DESCRIPTION
**Pull request by Marthyn**
Fix Bounty 889 https://assembly.com/helpful/bounties/889

I defined a constants with the dateformat so we can use it in the future too.

### CODE REVIEW

**Comment by wesleylancel** [comment]
Nice work @Marthyn!

I hadn't seen the bounty before, but personally prefer a format that doesn't confuse people from either Europe or the US. In this case I'd probably rather use a text month. What do you think @vanstee?

**Comment by Marthyn** [comment]
Now:
screen shot 2015-02-27 at 11 42 08

Proposed:
screen shot 2015-02-27 at 11 42 54

**Comment by Marthyn** [comment]
Btw i was confused when i opened the views folder, i first started changing things in like app/views/assignment_events/_assignment_event.html.erb but it seems like that code is not used at all anymore because it's all in ReactJS?

**Comment by vanstee** [comment]
Yeah I agree @wesleylancel. Thanks @Marthyn, looks good. Could you ping me on the Assembly bounty for this? Or, if one doesn't exist whip one up real quick so I can award you some coins.

**Pull request merged**
